
import streamlit as st
from groq import Groq
import re
import urllib.parse

# --- সেটিংস ---
AGENT_NAME = "Sara"
USER_NAME = "Skylord Suvo"

st.set_page_config(page_title=AGENT_NAME, page_icon="🤖", layout="wide")
st.title(f"🤖 {AGENT_NAME} - Advanced AI Voice & Image CEO")

# API Key
client = Groq(api_key="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")

if "messages" not in st.session_state:
    st.session_state.messages = [
        {
            "role": "system",
            "content": f"You are {AGENT_NAME}, the loyal AI CEO of {USER_NAME}. You can chat, write code, and generate images. If {USER_NAME} asks for an image, output 'IMAGE_PROMPT: [Description]'. Keep responses short for voice clarity."
        }
    ]

# ভয়েস শোনানোর ফাংশন
def speak_text(text):
    clean_text = re.sub(r'\[.*?\]', '', text)
    tts_url = f"https://translate.google.com/translate_tts?ie=UTF-8&q={urllib.parse.quote(clean_text)}&tl=bn&client=tw-ob"
    st.audio(tts_url, format="audio/mp3")

for message in st.session_state.messages:
    if message["role"] != "system":
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

if prompt := st.chat_input("সারা-কে কমান্ড দিন..."):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        try:
            response = client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=st.session_state.messages,
                temperature=0.7,
            )
            full_response = response.choices[0].message.content
            st.markdown(full_response)
            speak_text(full_response)
            
            if "IMAGE_PROMPT:" in full_response:
                image_desc = full_response.split("IMAGE_PROMPT:")[1].strip()
                image_url = f"https://pollinations.ai/p/{urllib.parse.quote(image_desc)}?width=1024&height=1024&seed=42&model=flux"
                st.image(image_url, caption="Generated by Sara")

            st.session_state.messages.append({"role": "assistant", "content": full_response})
        except Exception as e:
            st.error(f"Error: {e}")
            
